### ISSUE TITLE
FP101

### ISSUE THREAD

**Issue by MaikeMorrison** [FlukeAndFeather/jese4sci-FP#16]
Jenni, Chih-Fu, and I will be looking at 
https://www.nature.com/articles/nature25504

and aim to reproduce parts of figures 3 or 4.

**Comment by FlukeAndFeather** [comment]
Cool! Looks like you'll have some interesting functions to write. I'm excited to see how you implement this:

> Dynamic stability is computed as the absolute value of the real part of the dominant eigenvalue of the interaction matrix at each time point.
