### ISSUE TITLE
FP201 (Hannah, Ronghao, Raeline)

### ISSUE THREAD

**Issue by raecv** [FlukeAndFeather/jese4sci-FP#17]
1. The data is an .xlsx spreadsheet. It contains data from five different studies detailing COVID-19 transmissions between infected people and infectees. The columns delineate the study, the time of recorded infections, and (in some cases) the confidence intervals for when the people were likely infected for each pair.

2. The link to data (Figure 2-source data) is in the legend of the figure (https://cdn.elifesciences.org/articles/65534/elife-65534-fig2-data1-v2.xlsx), as well as in the Github hyperlink for the paper, under the data session (https://github.com/will-s-hart/COVID-19-Infectiousness-Profile/blob/main/Data/transmission_pair_data.xlsx).

3. The data seems complete. Even though there are missing datapoints, that’s only because they are using data from other papers. The code for reproducing the figure is available in throughout the other folders in on the GitHub repository (Results, Plotting Code, Functions, Scripts).

**Comment by FlukeAndFeather** [comment]
Looks like you picked an article with well-curated data and code! Looking forward to your modular design sketch.

**Comment by hffung** [comment]
@raecv @ronghao94
1. The data are in an Excel spreadsheet with the following variables:

- taxonomic information: order, family, genus, species
- physiological measurements: mass (g), basal metabolic rate (in W and in kJ/h), temperature
- reference of data source
- other factors that might affect metabolic rate: food type, habitat, climate, substrate, torpor, islands, mountains

2. The data were published with the journal article: https://static-content.springer.com/esm/art%3A10.1038%2Fnature08920/MediaObjects/41586_2010_BFnature08920_MOESM90_ESM.xls

3. The dataset appears to be complete :)
