### ISSUE TITLE
FP 201

### ISSUE THREAD

**Issue by MaikeMorrison** [FlukeAndFeather/jese4sci-FP#23]
Q1 - Provide a short description of the dataset. What is the data? What type of data is it? What format is it in?

The data is a csv file containing abundance of 15 different species of fish sampled off the coast of Japan every fortnight for 12 years. There is no missing data! 😮 

Q2 - Where did you find the data? Feel free to provide links, repository names, etc.

The data was available for download as a supplementary file hosted on Zenodo. It was in the form of a zip file that included nicely numbered R scripts, a data folder, a folder of R functions, a Readme file, etc. 

Q3 - Is the dataset complete? Do you have everything you need to replicate the result you're interested in?

It seems to be complete! We ran into some issues getting the correct version of a package that was required, but we downloaded the earliest possible version and it seems to be working so far.

**Comment by FlukeAndFeather** [comment]
Excellent!
