### ISSUE TITLE
FP101

### ISSUE THREAD

**Issue by ghost** [FlukeAndFeather/jese4sci-FP#24]
We will be replicating figure 1 from Kolokotrones et al. 2010

[Curvature in metabolic scaling](https://doi-org.stanford.idm.oclc.org/10.1038/nature08920)

Summary: It is widely assumed that basal metabolic rate increases with body mass according to a power law (i.e., linear on the log scale). The authors use data from >600 mammals to show that the relationship between body mass and basal metabolic rate is not log-linear, and thus is not best described by a simple power law relationship.

Challenge: Using the supplementary data, fit regression models with linear and quadratic effects of body mass on basal metabolic rate, excluding orcas and elephants. Plot the data and the resulting curves, with orca and elephants highlighted in the resulting plot and legend. Plot the resulting slopes as a function of body mass on a second panel.

**Comment by FlukeAndFeather** [comment]
Good choice, one of my favorite papers!
