### ISSUE TITLE
FP 201

### ISSUE THREAD

**Issue by ghost** [FlukeAndFeather/jese4sci-FP#26]
Q1

Provide a short description of the dataset. What is the data? What type of data is it? What format is it in?

A table in csv format. Measurements of basal metabolic rates and body mass of 637 species collected from a range of papers. 

Q2

Where did you find the data? Feel free to provide links, repository names, etc.

Supplementary information: [link](https://static-content.springer.com/esm/art%3A10.1038%2Fnature08920/MediaObjects/41586_2010_BFnature08920_MOESM90_ESM.xls)

Q3

Is the dataset complete? Do you have everything you need to replicate the result you're interested in?

Yes!

**Comment by FlukeAndFeather** [comment]
👍🏻👍🏻👍🏻
