### ISSUE TITLE
FP202

### ISSUE THREAD

**Issue by ShirleyJenniferSerranoRojas** [FlukeAndFeather/jese4sci-FP#29]
Workflow
**Function1 data rearrangement**
Input : num_for_smapc; d_name
Rearrange the data so that intraspecific interactions are in the first row for each species
Output: new_nums (rearranged data)

**Function 2 Quantify interaction and extract pairs of interaction needed for plotting**
Input: new_nums; biw_data
Output:  int_timeseries (time series for every pair of species interaction)

**Function 3  3D plot for the time series data**
Input: int_timeseries 
Output:  Figure 2A from the paper: Ushio, M., Hsieh, Ch., Masuda, R. et al. Fluctuating interaction network and time-varying stability of a natural fish community. Nature 554, 360–363 (2018). https://doi.org/10.1038/nature25504

**Comment by FlukeAndFeather** [comment]
cc @yehchihfu @MaikeMorrison

Looks great! We've already talked about the details for these functions, so I think you're on the right track.
