### ISSUE TITLE
FP201

### ISSUE THREAD

**Issue by Tatianabellagio** [FlukeAndFeather/jese4sci-FP#30]
Q1

Provide a short description of the dataset. What is the data? What type of data is it? What format is it in?

There are 5 sets of data, gene expression data from Qpcr
The data is in csv, xlsx and fasta format. 

Q2

Where did you find the data? Feel free to provide links, repository names, etc.

We found the data through the supplementary materials (https://royalsocietypublishing.org/doi/suppl/10.1098/rspb.2020.0239). The files were stored in Dryad (https://datadryad.org/stash/dataset/doi:10.5061/dryad.zcrjdfn7h). The code was in the supplementary section S2 for both Fig 2A and Fig 2B.

Q3

Is the dataset complete? Do you have everything you need to replicate the result you're interested in?

The dataset is complete, but the code they use to plot it is missing preprocessing steps as well as the code for the final publishable figure. The output of the script in their supplemental material produces a “raw” version of the published Fig. 2B.

**Comment by FlukeAndFeather** [comment]
Cool cool cool. For the purposes of this class, a "raw" figure is totally acceptable.

**Comment by FlukeAndFeather** [comment]
cc @sebatoroarana @gpreising
